name: GuitarSkater
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08921
title: This is my home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75152024-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#710000'
    - '#dc071d'
    - '#fe7d23'
    - '#fefb7a'
  brandStrength: 0.3041112588252872
  lightness: 0.3013606427703053
  saturation: 0.34889464103616774
  rhythmicContrast: 0.6094944116193801
purpose: []
